modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory

issueTrackerURL="https://github.com/EricHedengren/StandardMaterials/issues" #optional

[[mods]] #mandatory

modId="standardmaterials" #mandatory

version="1.2.0" #mandatory

displayName="Standard Materials" #mandatory

updateJSONURL="https://gist.githubusercontent.com/EricHedengren/f7d07eea9072592838f24d2889713e6f/raw" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/standardmaterials" #optional

logoFile="icon.png" #optional

credits="Isaac, Michael, Curseforge commenters, and the Internet" #optional

authors="BaconBombingDeveloper" #optional

description='''
This mod fully implements obsidian and emerald items to the game by adding them to everything normal items are apart of. You can even find them in normal structure chests! Obsidian items are extremely durable, and emerald items have high efficiency.
'''

[[dependencies.standardmaterials]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.standardmaterials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
