modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory

issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/baconbombingmod" #optional

[[mods]] #mandatory

modId="baconbombingmod" #mandatory

version="1.1.1" #mandatory

displayName="Obsidian and Emerald Tools" #mandatory

updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/baconbombingmod" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/baconbombingmod" #optional

logoFile="emerald_sword.png" #optional

credits="Thank you Isaac and Michael for helping me with ideas! Thank you to my curseforge commenters for helping me fix bugs! Thanks to the internet for having so much information!" #optional

authors="BaconBombingDeveloper" #optional

description='''
This mod adds obsidian and emerald tools to the game. Obsidian tools are extremely durable, and emerald tools have high efficiency and attack damage.
'''

[[dependencies.baconbombingmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.baconbombingmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
