modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory

issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/baconbombingmod/issues" #optional

[[mods]] #mandatory

modId="baconbombingmod" #mandatory

version="1.1.2" #mandatory

displayName="Obsidian and Emerald Tools" #mandatory

updateJSONURL="http://curseforge.com/minecraft/mc-mods/baconbombingmod/download" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/baconbombingmod" #optional

logoFile="obsidian_and_emerald_tools.png" #optional

credits="Isaac, Michael, Curseforge commenters, and the Internet" #optional

authors="BaconBombingDeveloper" #optional

description='''
This mod adds obsidian and emerald tools to the game. Obsidian tools are extremely durable, and emerald tools have high efficiency and attack damage.
'''

[[dependencies.baconbombingmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.baconbombingmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
