modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory

issueTrackerURL="https://github.com/EricHedengren/StandardMaterials/issues" #optional

[[mods]] #mandatory

modId="standardmaterials" #mandatory

version="1.1.3" #mandatory

displayName="Standard Materials" #mandatory

updateJSONURL="https://gist.githubusercontent.com/EricHedengren/f7d07eea9072592838f24d2889713e6f/raw" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/standardmaterials" #optional

logoFile="obsidian_and_emerald_tools.png" #optional

credits="Isaac, Michael, Curseforge commenters, and the Internet" #optional

authors="BaconBombingDeveloper" #optional

description='''
This mod adds obsidian and emerald tools to the game. Obsidian tools are extremely durable, and emerald tools have high efficiency and attack damage.
'''

[[dependencies.standardmaterials]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.standardmaterials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
